### ISSUE TITLE
Put order in repo names

### ISSUE THREAD

**Issue by tonofll** [databeacon/level5-schemas#23]
**Describe the bug**
**Firehose**
schemas/firehose/flifo
schemas/firehose/position
**Stream**
**REMOVE**: 
- schemas/stream/firehose-flifo (same schema than schemas/firehose/flifo)
- schemas/stream/firehose-position (same schema than schemas/firehose/position)

**KEEP**:
- schemas/stream/flifo (Schema of flifo Delta table)
- schemas/stream/flights (Schema of flights Ehub
- schemas/stream/current_positions (Schema of current positions Delta cache)
- schemas/stream/blender (Blender schema)
- schemas/stream/pcds
- schemas/stream/ncts

**Comment by dmartr** [comment]
This was fixed by #29
